# Contains IDs, private keys, etc.
# THIS FILE CONTAINS SENSITIVE INFO
# ALWAYS KEEP THIS FILE PRIVATE

# You'll need a Developed Application on the Reddit API: https://old.reddit.com/prefs/apps/
[reddit]
client_id = "REDDIT API CLIENT ID"
client_secret = "REDDIT API CLIENT SECRET"
user_agent = "2ootbot"

# You'll need a Twitter API developer account
[twitter]
consumer_key = "TWITTER API KEY"
consumer_secret = "TWITTER API KEY SECRET"
access_token = "TWITTER ACCESS TOKEN"
access_token_secret = "TWITTER ACCESS TOKEN SECRET"